@'
# ============================================================
# Rx: Add Paper 6 section (holonomy + CKM/PMNS) and build MASTER
# Fixed: LaTeX-safe here-strings (no $() expansion)
# ============================================================

param(
  [string]$RepoRoot = "C:\Users\Your Name Here\Desktop\Golden_Unification"
)

function Ensure-Dir {
  param([Parameter(Mandatory=$true)][string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path | Out-Null
    Write-Host "Created directory: $Path" -ForegroundColor Green
  } else {
    Write-Host "Directory exists:  $Path" -ForegroundColor DarkGray
  }
}

function Write-UTF8 {
  param(
    [Parameter(Mandatory=$true)][string]$Path,
    [Parameter(Mandatory=$true)][string]$Content
  )
  $Content | Set-Content -Path $Path -Encoding UTF8
  Write-Host "Wrote file:         $Path" -ForegroundColor Green
}

function Insert-InputLine {
  param(
    [Parameter(Mandatory=$true)][string]$MasterTex,
    [Parameter(Mandatory=$true)][string]$InputLine
  )

  $raw = Get-Content -Path $MasterTex -Raw -Encoding UTF8

  if ($raw -match [regex]::Escape($InputLine)) {
    Write-Host "Already present in:  $MasterTex" -ForegroundColor DarkGray
    Write-Host "  = $InputLine" -ForegroundColor DarkGray
    return
  }

  if ($raw -match "\\end\{document\}") {
    $raw2 = $raw -replace "\\end\{document\}", ($InputLine + "`r`n`r`n\end{document}")
    $raw2 | Set-Content -Path $MasterTex -Encoding UTF8
    Write-Host "Inserted into:      $MasterTex" -ForegroundColor Green
    Write-Host "  + $InputLine" -ForegroundColor Green
    return
  }

  Add-Content -Path $MasterTex -Value ("`r`n" + $InputLine + "`r`n") -Encoding UTF8
  Write-Host "Appended to:        $MasterTex" -ForegroundColor Yellow
  Write-Host "  + $InputLine" -ForegroundColor Yellow
}

# Paths
$papersDir   = Join-Path $RepoRoot "papers"
$sectionsDir = Join-Path $papersDir "sections"
$masterTex   = Join-Path $papersDir "MASTER.tex"

Ensure-Dir $sectionsDir

# ----------------------------
# Paper 6 section content
# NOTE: single-quoted here-string to prevent PowerShell from interpreting LaTeX $()
# ----------------------------
$paper6 = @'
% ============================================================
% Paper VI section: holonomy, CKM/PMNS verification, CP phases
% File: papers/sections/06_holonomy_mixing.tex
% ============================================================

\section{Holonomy-phase model for CKM and PMNS CP violation}
\label{sec:holonomy_mixing}

\subsection{Scope and deliverables}
This section records the \emph{verification-grade} mixing and CP-violation checks used in the Golden Unification program. The objective is not to re-derive the Standard Model flavor formalism, but to (i) define the observables we match, (ii) state the geometric/holonomy hypothesis precisely, and (iii) provide a reproducible computational audit trail that produces a fixed results block suitable for peer review.

\subsection{CKM and PMNS parameterization}
Let $V_{\mathrm{CKM}}$ and $U_{\mathrm{PMNS}}$ denote the quark and lepton mixing matrices in the standard three-angle/one-phase parameterization. We use the sines
\begin{equation}
s_{12} \equiv \sin\theta_{12}, \qquad
s_{23} \equiv \sin\theta_{23}, \qquad
s_{13} \equiv \sin\theta_{13},
\end{equation}
together with the Dirac CP phase $\delta$. A convenient invariant of CP violation is the Jarlskog determinant,
\begin{equation}
J \;=\; c_{12}c_{23}c_{13}^{2}\, s_{12}s_{23}s_{13}\,\sin\delta,
\label{eq:jarlskog}
\end{equation}
with $c_{ij}=\cos\theta_{ij}$. Equation \eqref{eq:jarlskog} is used as an internal consistency check once $\delta$ is fixed.

\subsection{Holonomy hypothesis for the CP phase}
The working hypothesis is that the Dirac phase is controlled (directly or indirectly) by a geometric holonomy angle $\theta_{\star}$ associated with the same discrete structure organizing mass data. Operationally, the verification task is:

\begin{enumerate}
\item take fixed input $(s_{12},s_{23},s_{13})$ from global fits,
\item take a predicted holonomy angle $\theta_{\star}$ (in degrees),
\item scan $\delta \in [0^\circ,360^\circ]$ on a dense grid,
\item select $\delta$ by a pre-registered matching rule (below),
\item report $\delta$ and the derived $J$.
\end{enumerate}

We support two matching rules:
\begin{align}
\texttt{match\_deg:}\quad & \min_{\delta}\;|\delta-\theta_{\star}|, \\
\texttt{match\_sin:}\quad & \min_{\delta}\;|\sin\delta-\sin\theta_{\star}|.
\end{align}
The \texttt{match\_sin} rule is preferred when the geometric mechanism predicts $\sin\theta_{\star}$ (or is only defined modulo $\delta\mapsto 180^\circ-\delta$). Both are reported for CKM as an internal cross-check.

\subsection{Reproducible computation}
All scans are generated by the repository script:
\begin{equation}
\texttt{code/verify\_mixing.py}.
\end{equation}
The script prints the inputs, the best-fit $\delta$, the match score, and the resulting $J$, then writes a LaTeX-ready results block to:
\begin{equation}
\texttt{shared/paperV\_mixing\_results.tex}.
\end{equation}
This file is treated as an \emph{externalized, versioned artifact} and is included verbatim in the paper build (no manual edits).

\subsection{Verified results block (CKM + PMNS)}
\input{../shared/paperV_mixing_results.tex}

\subsection{Interpretation and falsifiability}
The CKM result demonstrates that the scan-and-match protocol can reproduce the observed quark-sector CP phase at the level of the scan grid resolution when the predicted holonomy angle is chosen consistently with the matching rule. The PMNS extension is structurally identical: once the leptonic $(s_{12},s_{23},s_{13})$ are supplied and a leptonic $\theta_{\star}$ is specified, the same audit pipeline yields a definite $\delta_{\mathrm{PMNS}}$ and $J_{\mathrm{PMNS}}$.

This section is falsifiable in three ways:
\begin{enumerate}
\item \textbf{Stability under updated global fits:} replacing the input sines with newer global-fit values must not destroy the holonomy matching beyond stated tolerances.
\item \textbf{Pre-registered matching rule:} the choice of matching rule (\texttt{match\_sin} vs \texttt{match\_deg}) must be fixed \emph{before} examining outcomes for new datasets or revised predictions.
\item \textbf{Cross-sector coherence:} if the same underlying geometric mechanism is claimed to control both quark and lepton phases, the inferred $\theta_{\star}$ values should satisfy the model's internal relations (to be stated explicitly in the consolidated theory paper).
\end{enumerate}

\subsection{What Paper VII will add}
Paper VII will extend this from verification to \emph{model-building}: specifying the geometric origin of $\theta_{\star}$ (e.g., an $\Afive$-associated holonomy class), connecting it to discrete data in the mass lattice program, and stating genuine predictions (including error bars and multiplicities) that can be pre-registered.
'@

$paper6Path = Join-Path $sectionsDir "06_holonomy_mixing.tex"
Write-UTF8 $paper6Path $paper6

# Insert \input into MASTER.tex
if (-not (Test-Path -LiteralPath $masterTex)) {
  throw "MASTER.tex not found at: $masterTex"
}

$inputLine = "\input{sections/06_holonomy_mixing.tex}"
Insert-InputLine -MasterTex $masterTex -InputLine $inputLine

# Build
Write-Host ""
Write-Host "Compiling MASTER.tex..." -ForegroundColor Cyan
Push-Location $papersDir
pdflatex .\MASTER.tex | Out-Null
Pop-Location

$masterPdf = Join-Path $papersDir "MASTER.pdf"
$masterLog = Join-Path $papersDir "MASTER.log"

Write-Host ""
if (Test-Path -LiteralPath $masterPdf) {
  Write-Host "Build OK:" -ForegroundColor Green
  Write-Host "  PDF: $masterPdf" -ForegroundColor Green
  Write-Host "  LOG: $masterLog" -ForegroundColor Green
} else {
  Write-Host "Build failed. Check LOG: $masterLog" -ForegroundColor Red
}
'@ | Set-Content -Path .\rx_add_paper6_and_build.ps1 -Encoding UTF8
